### PR TITLE
Showcase: Marmelab

### PR DESCRIPTION
**Pull request by DirtyF**
Made with Gatsby

### CODE REVIEW

**Comment by budparr** [comment]
You are on fire! And it's much appreciated. I should just give you push access to the repo if that works for you.

**Comment by DirtyF** [comment]
As you prefer, I searched for `jekyll-site`and `hugo-site` on GitHub, I doubt I can keep that rythm 🥁

**Comment by budparr** [comment]
Yeah, I don't expect anything necessarily, but I'm glad to have the help. I add articles via Serum so that's pretty easy to keep up with.

**Comment by DirtyF** [comment]
What is Serum?

**Comment by budparr** [comment]
It's a Chrome app to easily post to Jekyll sites. It's pretty much the reason I have links as posts https://chrome.google.com/webstore/detail/serum/ffboflhdigfmnnokjjcmfipgehggjhlj?hl=en

**Pull request merged**
