### PR TITLE
Add Cecil

### PR DESCRIPTION
**Pull request by ArnaudLigny**
See the content of the file for details! :-)

### CODE REVIEW

**Comment by budparr** [comment]
@Narno thank you! I will merge this today.

**Comment by ArnaudLigny** [comment]
:wave:

**Review by DirtyF — APPROVED** [review]

**Comment by budparr** [comment]
@Narno Apologies. I have no idea what happened to me there, other than being head-spinningly busy. Thank you, @DirtyF !

**Comment by ArnaudLigny** [comment]
Don't worry @budparr: there was no urgency; Thx to Frank and you! :-)

**Pull request merged**
