### PR TITLE
Add feed for the Showcase

### PR DESCRIPTION
**Pull request by DirtyF**
This would allow to post new showcase entries to Twitter or to a Slack channel :)

### CODE REVIEW

**Comment by DirtyF** [comment]
@budparr would be nice to have a Netlify's preview on PRs for this repo 👼

**Comment by DirtyF** [comment]
view-source:https://showcase-feed--the-new-dynamic.netlify.com/showcase/index.xml

**Comment by budparr** [comment]
Hey, @DirtyF I don't know how to turn the previews on. Seems like that's always been automatic. Do you know? At any rate, I'll merge this.

**Comment by DirtyF** [comment]
@budparr For deploy preview notifications you need to use a GitHub Token and add a webhook as explained here: https://www.netlify.com/docs/webhooks/#github-commit-statuses

**Comment by budparr** [comment]
Thank you. Should be set now. I have no idea why it wasn't set for this repo, as I think it is for all the others.

**Pull request merged**
