### PR TITLE
Videos page

### PR DESCRIPTION
**Pull request by mdxprograms**
Added a videos page. It works off of the _data/videos information. I separated the naming based on video type. The only video added is just a youtube embed at the moment inside of _data/videos/youtube.yml.

I added an include that loops through the videos based on the include variable of `type` to associate the data file needed. Once other video sources are added other than youtube the include will need a conditional for video type to add the correct iframe code and possible styling changes.

I'm adding this PR as **_just a review_** for now to see what you think of the setup and if you might have any suggestions or preferences on the setup/additions of videos.

Thanks!

### CODE REVIEW

**Comment by budparr** [comment]
Awesome, thank you. First glance at the code it looks good; pretty straightforward. I can have a closer look over the weekend.

**Comment by mdxprograms** [comment]
Great! I wasn't able to get my video stylesheet to be recognized using the `@import` I think I may be missing something there :/ but I added the responsive setup for it, so once the stylesheet is recognized it should make the videos responsive.

A couple other video options on how to pull them in were:

1. pull from a youtube playlist on build and have a ruby script save the playlist data to the data file
2. use something like airtable to enter the information and then do something similar to ^

I was trying to think of a dynamic way to update the information without having to enter it manually into the data file but maybe it's easier for now until a better idea comes along for more contributors or something?

**Comment by budparr** [comment]
Do you know this: https://staticman.net/

**Comment by mdxprograms** [comment]
I've messed with it before for a contact form when he started it, but haven't played with it much since. I know it creates a new data file with a referenced date or something similar tagged to the title of the file. Is it possible to have it append data to a file? If not we could always create a youtube folder inside of the videos folder in `_data` and then loop through those files for each youtube entry.

**Comment by budparr** [comment]
I think there are some Vimeo videos, too, by the way. I know there's a Smashing Mag video in there and that's what they use. 

I think staticman appends to the file, yes.

**Comment by mdxprograms** [comment]
cool, ok I can take a look at setting that up.

**Comment by budparr** [comment]
Hey, @mdxprograms I went ahead and merged this. I'll start adding some videos and such. Let me know your thoughts on staticman whenever you get a chance, or any other method you think would be good.
Have a great weekend!

**Pull request merged**
