### PR TITLE
Add Meili and module

### LINKED ISSUE #123: Use Search Module front + Meili
@budparr what do you think?

### PR DESCRIPTION
**Pull request by regisphilibert**
Fixes #123

### CODE REVIEW

**Comment by DirtyF** [comment]
Showcase thumbs aren't showing on that page. 
Note: This project is now archived, the author recommends tot use Next.js instead, so should be also archived on TND I guess.
<details><summary>Browser metadata</summary>





```
Path:      /tool/phenomic/
Browser:   Safari 14.1.1 on Mac OS 10.15.7
Viewport:  1440 x 820 @2x
Language:  fr-fr
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-124--thenewdynamic-org.netlify.app%2Ftool%2Fphenomic%2F&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x820&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-124--thenewdynamic-org.netlify.app/tool/phenomic/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60b94349099cf800079af71a&commentID=60b952af73404310fda1bd74&resolution=resolved)

**Comment by DirtyF** [comment]
Search is working fine, just noticed a weird UI glitch when your search: 
https://www.loom.com/share/cf6d94cf7e1e4fc3a5216a8fce9c28c0
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Safari 14.1.1 on Mac OS 10.15.7
Viewport:  1440 x 848 @2x
Language:  fr-fr
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-124--thenewdynamic-org.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x848&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-124--thenewdynamic-org.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60b94349099cf800079af71a&commentID=60b953b1e0e9bc13a7c7d2ab&resolution=resolved)

**Comment by regisphilibert** [comment]
> Showcase thumbs aren't showing on that page. 

Thanks @DirtyF I addressed on `main`.

**Comment by regisphilibert** [comment]
> Search is working fine, just noticed a weird UI glitch when your search:

Not seeing it anymore... wonder if you got caught in some branch back and forth.

**Pull request merged**
